apiVersion: apps/v1
kind: Deployment
metadata:
  name: Imageuploader
  labels:
    app: Imageuploader
spec:
  replicas: 3  # Number of instances of the application to deploy
  selector:
    matchLabels:
      app: Imageuploader
  template:
    metadata:
      labels:
        app: Imageuploader
    spec:
      containers:
      - name: Imageuploader
        image: galshed1107/django-app:latest
        ports:
        - containerPort: 8000
        
        # Add any additional environment variables, such as database credentials
 