apiVersion: v1
kind: Service
metadata:
  name: Imageuploader-server
spec:
  selector:
    app: Imageuploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Port where Django app is running inside container
  type: LoadBalancer  # Exposes the service to the internet (or use ClusterIP for internal access only)